app_forum/urls.py
from django.conf.urls import url
from .views import index, add_forum

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_forum', add_forum, name='add_forum'),
]

app_home/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    # url(r'^add_forum', add_forum, name='add_forum'),
]

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_forum.urls as app_forum
import app_home.urls as app_home
import app_profile.urls as app_profile
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^forum/', include(app_forum,namespace='app_forum')),
    url(r'^home/', include(app_home,namespace='app_home')),
    url(r'^profile/', include(app_profile,namespace='app_profile')),
    url(r'^$', RedirectView.as_view(url='/home/', permanent='true'), name='index'),
]

urls.py
from django.conf.urls import url
from .views import index, add_forum

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_forum', add_forum, name='add_forum'),
]

app_forum/models.py
from django.db import models

# Create your models here.
class Forum(models.Model):
    company_id = models.IntegerField(default=0)
    lowongan = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

app_home/models.py
from django.db import models

# Create your models here.

app_profile/models.py
from django.db import models

# Create your models here.

app_forum/forms.py
from django import forms

class Forum_Lowongan(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    lowongan_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukan deskripsi lowongan pekerjaan'
    }

    lowongan = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=lowongan_attrs))

app_forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from .forms import Forum_Lowongan
from .models import Forum


# Create your views here.
response = {}
def index(request):
    forum_list = Forum.objects.all()
    forum_latest = forum_list[::-1]
    page = request.GET.get('page', 1)
    paginator = Paginator(forum_latest, 5)
    try:
        forum = paginator.page(page)
    except PageNotAnInteger:
        forum = paginator.page(1)
    except EmptyPage:
        forum = paginator.page(paginator.num_pages)
    response['forum'] = forum
    response['forum_lowongan'] = Forum_Lowongan
    html = 'app_forum/app_forum.html'
    return render(request, html, response)

@csrf_exempt
def add_forum(request):
    if request.method == 'POST':
        company_id = request.POST['company_id']
        lowongan = request.POST['lowongan']
        forum = Forum(company_id=company_id,lowongan=lowongan)
        forum.save()
        return HttpResponseRedirect('/forum/')
    else:
        return HttpResponseRedirect('/forum/')

app_home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from app_forum.models import Forum
# Create your views here.
response = {}
def index(request):
    html = 'app_home/app_home.html'
    forum = Forum.objects.all()
    forum_list = forum[::-1]
    response['forum_list'] = forum_list
    return render(request, html, response)

app_profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.
response = {}
def index(request):
    html = 'app_profile/app_profile.html'
    return render(request,html,response)

app_forum/templates/app_forum/app_forum.html
{% extends "tugas2/layout/base.html" %} {% load staticfiles%} {% block content %}
<h1 class="main-title" id="forum-title">Forum Lowongan</h1>
<hr/>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="">
            {% csrf_token %}
            <textarea name="lowongan" type="text" class="todo-form-textarea" placeholder="Masukan deskripsi lowongan pekerjaan" required="required" id="id_lowongan"></textarea>
            <input id="submit" type="submit" class="btn btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <div class="forum-owner-info col-md-12">
            <h2 id="list-lowongan-title">Daftar Lowongan oleh</h2>
            <img id="lowongan-pic" src="">
            <h3 id="lowongan-owner"></h3>
        </div>
        <div class="forum-lowongan col-md-12">
            {% if forum %} {% for data in forum %}
            <p id="lowongan-detail">{{ data.lowongan }}</p>
            <p id="lowongan-date">{{ data.created_date }}</p>
            <hr>
            {% endfor %} {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada forum lowongan yang tersedia.
            </div>
            {% endif %}

            <div class="pagination col-md-12">
                <span class="step-links">
                    <ul class="pagination">
                    {% if forum.has_previous %}
                        <li><a href="?page=1">&laquo; first</a></li>
                        <li><a href="?page={{ forum.previous_page_number }}">previous</a></li>
                    {% endif %}
                    <li><span class="current">Page {{ forum.number }} of {{ forum.paginator.num_pages }}</span></li>
                    {% if forum.has_next %}
                        <li><a href="?page={{ forum.next_page_number }}">next</a></li>
                        <li><a href="?page={{ forum.next_page_number }}">last &raquo;</a></li>
                    {% endif %}
                    </ul>
                </span>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block script %}
<script>
    var logged_in;
    function onLinkedInLoad() {
        logged_in = IN.User.isAuthorized();
        if(logged_in){
            IN.Event.on(IN, "auth", getSessionCompanyData);
        }else{
            alert("Silakan masuk menggunakan akun LinkedIn Anda terlebih dahulu!");
            window.location = "{% url 'app_home:index' %}";
        }
    }

    function getSessionCompanyData() {
        document.getElementById("lowongan-owner").innerHTML = sessionStorage.getItem("company_name");
        document.getElementById("lowongan-pic").src = sessionStorage.getItem("company_logo");
    }

    var addLowongan = function(company_id, lowongan){
        $.ajax({
            method: "POST",
            url : "{% url 'app_forum:add_forum' %}",
            data : {
                company_id: company_id,
                lowongan: lowongan
            },
            success: function(success){
                console.log("Diskusi lowongan terbaru berhasil ditambahkan!");
                window.location = "{% url 'app_forum:index' %}";

            },
            error: function(error){
                console.log("Diskusi lowongan terbaru gagal ditambahkan!");
            }
        });
    };

    $("#form").submit(function(e){
        var company_id = sessionStorage.getItem("company_id");
        var lowongan = $("#id_lowongan").val();
        addLowongan(company_id, lowongan);
        e.preventDefault();
    });
</script>
{% endblock %}

app_home/templates/app_home/app_home.html
{% extends "tugas2/layout/base.html" %} {% load staticfiles%} {% block content %}
<div class="col-md-12 login"><script type="in/Login"></script></div>

<div id="feeds" style="display: none;">
    <p><a href="javascript:void(0);" onclick="logout()">Logout</a></p>
    <div class="row">
        <div class="company-data">
            <img id="logo" src="">
            <h3 id="name"></h3>
        </div>
          {% if forum_list %}
            {% for lowongan in forum_list %}
            <a class="list-group-item clearfix">{{ lowongan.lowongan }}<br>{{ lowongan.created_date }}</a>
                {% endfor %}
          {% else %}
          <div class="alert alert-danger text-center">
              <strong>Oops!</strong> Tidak ada lowongan yang tersedia.
          </div>
          {% endif %}

    </div>
</div>

<script type="text/javascript">
  console.log('asd');
  // Setup an event listener to make an API call once auth is complete
  var logged_in;
  function onLinkedInLoad() {
      console.log('mulai');
      logged_in = IN.User.isAuthorized();
      // IN.User.authorize(function() {
      //   if(!logged_in){
      //   window.location = "{% url 'app_profile:index' %}";
      //   }
      // });
        IN.Event.on(IN, "auth", function() {
          getCompanyData();

        });
  }

  // Use the API call wrapper to request the company's profile data
  function getCompanyData() {
  	// Masukin ID company lau
      var cpnyID = 13600560;
      IN.API.Raw("/companies/" + cpnyID + ":(id,name,description,logo-url,specialties,website-url,company-type)?format=json")
        .method("GET")
        .result(SaveCompanyData)
        .error(onError);
        document.getElementById('feeds').style.display = 'block';
  }
  function SaveCompanyData(data){

      console.log(data);
      //save to session
      sessionStorage.setItem("company_description",data.description);
      sessionStorage.setItem("company_id",data.id);
      sessionStorage.setItem("company_logo",data.logoUrl);
      sessionStorage.setItem("company_name",data.name);
      sessionStorage.setItem("company_type",data.companyType.name);
      sessionStorage.setItem("arrOfSpecialties",data.specialties.values);
      sessionStorage.setItem("company_web",data.websiteUrl);
      sessionStorage.setItem("company_description",data.description);
      //retreive
      var name = sessionStorage.getItem("company_name");
      var icon = sessionStorage.getItem("company_logo");
      //show in html
      document.getElementById("logo").src = icon;
      document.getElementById("name").innerHTML = name;

      if (!logged_in) {
        window.location = "{% url 'app_profile:index' %}";
      }
  }

  // Handle an error response from the API call
  function onError(error) {
      console.log(error);
  }

  // Destroy the session of linkedin
  function logout(){
      IN.User.logout(removeCompanyData);
  }
  // Remove profile data from page
  function removeCompanyData(){
      document.getElementById('feeds').remove();
      sessionStorage.clear();
      window.location = "{% url 'app_home:index' %}";
  }
</script>
{% endblock %}

app_profile/templates/app_profile/app_profile.html
{% extends "tugas2/layout/base.html" %} {% load staticfiles%} {% block content %}
<!DOCTYPE html>
<div class="profileData col-md-12">
    <h4 id="welcome"></h4>
    <h3 id="nameCompany"></h3>
    <div id="pictureCompany"></div>
    <div id="button"></div>
    <div id="info">
        <p id="typeCompany"></p>
        <p id="webCompany"></p>
        <p id="specialCompany"></p>
        <p id="describeCompany"></p>
    </div>
</div>
<script type="text/javascript">
    var logged_in;
    function onLinkedInLoad() {
        logged_in = IN.User.isAuthorized();
        if(logged_in){
            IN.Event.on(IN, "auth", getSessionCompanyData);
            munculButton();
        }else{
            alert("Silakan masuk menggunakan akun LinkedIn Anda terlebih dahulu!");
            window.location = "{% url 'app_home:index' %}";
        }
    }

    function getSessionCompanyData() {
        document.getElementById("welcome").innerHTML = 'Selamat Datang di LinkedIn Job!';
        document.getElementById("nameCompany").innerHTML = sessionStorage.getItem("company_name");
        document.getElementById("pictureCompany").innerHTML = '<img align="middle" src="' + sessionStorage.getItem("company_logo") + '"</img>';
        document.getElementById("typeCompany").innerHTML = 'Tipe Perusahaan : ' + sessionStorage.getItem("company_type");
        document.getElementById("webCompany").innerHTML = 'Web Perusahaan   : <a href="http://' + sessionStorage.getItem("company_web") + '/"> http://' + sessionStorage.getItem("company_web") + '/</a>';
        document.getElementById("specialCompany").innerHTML = 'Spesialitas  : ' + sessionStorage.getItem("arrOfSpecialties"); 
        document.getElementById("describeCompany").innerHTML = 'Deskripsi : ' + sessionStorage.getItem("company_description");
    }

    function munculButton(){
        document.getElementById("button").innerHTML =  '<a href="{% url 'app_forum:index' %}" class="btn btn-primary button-profile"> Lihat Forum </a> '
        + '<a href="" class="btn btn-danger button-profile"> Cari Mahasiswa </a>'
    }
</script>
{% endblock %}

templates/tugas2/layout/base.html
{% load staticfiles %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- bootstrap css -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Snippet" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <meta charset="UTF-8">
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
        api_key:   81te3jyuobt76t
        authorize: true
        lang:      en_US
        onLoad:    onLinkedInLoad
        scope: r_basicprofile r_emailaddress rw_company_admin w_share
    </script>
    <title>LinkedIn Job</title>
	{% block styles %}
	{% endblock %}
	<title>
        {% block title %} PPW A12 {% endblock %}
    </title>
</head>
<header>
  {% include "tugas2/partials/header.html" %}
</header>
<body class="Site">
    <content class="Site-content">
      <div class="container">
        {% block content %}
        <!-- content goes here -->
        {% endblock %}
  </div>
</content>
    <footer class="footer">
        {% block footer %} {% include "tugas2/partials/footer.html" %} {% endblock %}
    </footer>
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	{% block script %}

	{% endblock %}
</body>

templates/tugas2/partials/footer.html
{% load staticfiles %} {% load static %}
<div class="footer">
    <hr>
    <p>&copy; Made By Team A12 PPW 2017</p>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</script>

templates/tugas2/partials/header.html
<!-- templates/partials/header.html -->
{% load staticfiles %} {% load static %}

<nav class="navbar navbar-default navbar-fixed-top" style="background-color: #2E3131">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            <div>
                <a class="navbar-brand" href="{% url 'app_home:index' %}"><img src="{% static 'img/in.png' %}" width="25px" height="25px"></a>
            </div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a id="nav-profile"><span class="glyphicon glyphicon-user"></span> Profil</a></li>
                <li><a id="nav-forum"><span class="glyphicon glyphicon-search"></span> Forum</a></li>
                <!--<li><a id="nav-logout"><span class="glyphicon glyphicon-off"></span> Keluar</a></li>-->
			</ul>
        </div>
    </div>
</nav>